{{- $services := dict "book" (dict "root" "book" "port" .Values.bookService.service.port) "user" (dict "root" "user" "port" .Values.userService.service.port) "borrow" (dict "root" "borrow" "port" .Values.borrowService.service.port) -}}
{{- range $name, $svc := $services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.root }}-svc
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "library-e2e.labels" $ | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "library-e2e.name" $ }}
    app.kubernetes.io/component: backend
    app: {{ $name }}-service
---
{{- end }}
